version: '3.8'

services:
  mysql-db:
    build: ./mysql-container
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${CONTAINER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CONTAINER_DB_NAME}
      MYSQL_USER: ${CONTAINER_DB_USER}
      MYSQL_PASSWORD: ${CONTAINER_DB_USER_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql-db
      DB_USER: ${CONTAINER_DB_USER}
      DB_PASSWORD: ${CONTAINER_DB_USER_PASSWORD}
      DB_NAME: ${CONTAINER_DB_NAME}
      DB_PORT: ${DB_PORT}
      SECRET_TOKEN: ${SECRET_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data: