/*
-- Query: SELECT * FROM Countries
LIMIT 0, 1000

-- Date: 2025-01-08 20:22
*/
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (1,'Afghanistan','Provinces',34);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (2,'Albania','Counties',12);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (3,'Algeria','Provinces',58);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (4,'Andorra','Parishes',7);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (5,'Angola',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (6,'Antigua and Barbuda',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (7,'Argentina',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (8,'Armenia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (9,'Australia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (10,'Austria','States',9);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (11,'Azerbaijan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (12,'Bahamas',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (13,'Bahrain',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (14,'Bangladesh',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (15,'Barbados',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (16,'Belarus',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (17,'Belgium','Provinces',11);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (18,'Belize',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (19,'Benin',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (20,'Bhutan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (21,'Bolivia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (22,'Bosnia and Herzegovina',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (23,'Botswana',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (24,'Brazil',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (25,'Brunei',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (26,'Bulgaria',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (27,'Burkina Faso',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (28,'Burundi',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (29,'Cambodia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (30,'Cameroon',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (31,'Canada',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (32,'Cape Verde',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (33,'Central African Republic',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (34,'Chad',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (35,'Chile',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (36,'China',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (37,'Colombia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (38,'Comoros',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (39,'Costa Rica',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (40,'Croatia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (41,'Cuba',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (42,'Cyprus',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (43,'Czech Republic','Regions',14);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (44,'Democratic Republic of the Congo',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (45,'Denmark','Regions',5);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (46,'Djibouti',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (47,'Dominica',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (48,'Dominican Republic',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (49,'East Timor',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (50,'Ecuador',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (51,'Egypt',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (52,'El Salvador',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (53,'Equatorial Guinea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (54,'Eritrea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (55,'Estonia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (56,'Eswatini',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (57,'Ethiopia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (58,'Fiji',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (59,'Finland',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (60,'France','Regions',18);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (61,'Gabon',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (62,'Gambia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (63,'Georgia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (64,'Germany','States',16);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (65,'Ghana',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (66,'Greece',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (67,'Grenada',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (68,'Guatemala',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (69,'Guinea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (70,'Guinea-Bissau',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (71,'Guyana',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (72,'Haiti',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (73,'Honduras',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (74,'Hungary','Counties',20);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (75,'Iceland',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (76,'India',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (77,'Indonesia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (78,'Iran',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (79,'Iraq',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (80,'Ireland','Counties',26);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (81,'Israel',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (82,'Italy','Regions',20);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (83,'Ivory Coast',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (84,'Jamaica',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (85,'Japan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (86,'Jordan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (87,'Kazakhstan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (88,'Kenya',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (89,'Kiribati',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (90,'Kosovo',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (91,'Kuwait',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (92,'Kyrgyzstan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (93,'Laos',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (94,'Latvia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (95,'Lebanon',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (96,'Lesotho',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (97,'Liberia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (98,'Libya',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (99,'Liechtenstein','Municipalities',11);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (100,'Lithuania',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (101,'Luxembourg','Cantons',12);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (102,'Madagascar',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (103,'Malawi',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (104,'Malaysia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (105,'Maldives',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (106,'Mali',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (107,'Malta','Regions',6);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (108,'Marshall Islands',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (109,'Mauritania',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (110,'Mauritius',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (111,'Mexico',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (112,'Micronesia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (113,'Moldova',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (114,'Monaco',NULL,1);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (115,'Mongolia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (116,'Montenegro',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (117,'Morocco',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (118,'Mozambique',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (119,'Myanmar',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (120,'Namibia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (121,'Nauru',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (122,'Nepal',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (123,'Netherlands','Provinces',15);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (124,'New Zealand',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (125,'Nicaragua',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (126,'Niger',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (127,'Nigeria',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (128,'North Korea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (129,'North Macedonia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (130,'Norway',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (131,'Oman',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (132,'Pakistan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (133,'Palau',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (134,'Panama',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (135,'Papua New Guinea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (136,'Paraguay',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (137,'Peru',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (138,'Philippines',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (139,'Poland','Voivodeships',16);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (140,'Portugal','Districts',20);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (141,'Qatar',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (142,'Republic of the Congo',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (143,'Romania',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (144,'Russia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (145,'Rwanda',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (146,'Saint Kitts and Nevis',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (147,'Saint Lucia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (148,'Saint Vincent and the Grenadines',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (149,'Samoa',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (150,'San Marino','Castelli',9);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (151,'São Tomé and Príncipe',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (152,'Saudi Arabia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (153,'Senegal',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (154,'Serbia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (155,'Seychelles',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (156,'Sierra Leone',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (157,'Singapore',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (158,'Slovakia','Regions',8);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (159,'Slovenia','Statistical Regions',12);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (160,'Solomon Islands',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (161,'Somalia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (162,'South Africa',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (163,'South Korea',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (164,'South Sudan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (165,'Spain','Autonomous Communities',20);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (166,'Sri Lanka',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (167,'Sudan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (168,'Suriname',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (169,'Sweden',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (170,'Switzerland','Cantons',26);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (171,'Syria',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (172,'Taiwan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (173,'Tajikistan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (174,'Tanzania',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (175,'Thailand',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (176,'Togo',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (177,'Tonga',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (178,'Trinidad and Tobago',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (179,'Tunisia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (180,'Turkey',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (181,'Turkmenistan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (182,'Tuvalu',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (183,'Uganda',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (184,'Ukraine',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (185,'United Arab Emirates',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (186,'United Kingdom',NULL,156);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (187,'United States',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (188,'Uruguay',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (189,'Uzbekistan',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (190,'Vanuatu',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (191,'Vatican City',NULL,1);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (192,'Venezuela',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (193,'Vietnam',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (194,'Yemen',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (195,'Zambia',NULL,0);
INSERT INTO `` (`idCountry`,`Name`,`RegionName`,`RegionCount`) VALUES (196,'Zimbabwe',NULL,0);
