/*
-- Query: SELECT * FROM EuropeanRegions
LIMIT 0, 1000

-- Date: 2025-01-08 20:27
*/
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (1,'Andreas','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (2,'Arbory and Rushen','Parish','Isle of Man','[\"Arbrory\", \"Rushen\"]',NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (3,'Ballaugh','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (4,'Braddan','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (5,'Bride','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (6,'Castletown','Town','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (7,'Douglas','Town','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (8,'Garff','Parish','Isle of Man','[\"Laxey\", \"Lonan\", \"Maughold\"]',NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (9,'German','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (10,'Jurby','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (11,'Lezayre','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (12,'Malew','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (13,'Marown','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (14,'Michael','District','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (15,'Onchan','District','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (16,'Patrick','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (17,'Peel','Town','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (18,'Port Erin','Village','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (19,'Port Saint Mary','Village','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (20,'Ramsey','Town','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (21,'Santon','Parish','Isle of Man',NULL,NULL,29);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (22,'Bath and North East Somerset','Unitary Authority','England','[\"Somerset\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (23,'Bedford','Unitary Authority','England','[\"Bedfordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (24,'Blackburn with Darwen','Unitary Authority','England','[\"Lancashire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (25,'Blackpool','Unitary Authority','England','[\"Lancashire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (26,'Bournemouth, Christchurch and Poole','Unitary Authority','England','[\"Dorset\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (27,'Bracknell Forest','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (28,'Brighton and Hove','Unitary Authority','England','[\"East Sussex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (29,'Bristol','County and Unitary Authority','England','[\"Bristol\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (30,'Buckinghamshire','Unitary Authority','England','[\"Buckinghamshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (31,'Cambridgeshire','County','England','[\"Cambridgeshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (32,'Central Bedfordshire','Unitary Authority','England','[\"Bedfordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (33,'Cheshire East','Unitary Authority','England','[\"Cheshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (34,'Cheshire West and Chester','Unitary Authority','England','[\"Cheshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (35,'City of London','County','England','[\"City of London\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (36,'Cornwall','Unitary Authority','England','[\"Cornwall\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (37,'County Durham','Unitary Authority','England','[\"Durham\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (38,'Cumberland','Unitary Authority','England','[\"Cumbria\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (39,'Darlington','Unitary Authority','England','[\"Durham\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (40,'Derby','Unitary Authority','England','[\"Derbyshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (41,'Derbyshire','County','England','[\"Derbyshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (42,'Devon','County','England','[\"Devon\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (43,'Dorset','County','England','[\"Dorset\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (44,'East Riding of Yorkshire','Unitary Authority','England','[\"East Riding of Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (45,'East Sussex','County','England','[\"East Sussex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (46,'Essex','County','England','[\"Essex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (47,'Gloucestershire','County','England','[\"Gloucestershire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (48,'Greater London','County','England','[\"Greater London\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (49,'Greater Manchester','County','England','[\"Greater London\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (50,'Halton','Unitary Authority','England','[\"Cheshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (51,'Hampshire','County','England','[\"Hampshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (52,'Hartlepool','Unitary Authority','England','[\"Durham\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (53,'Herefordshire','County and Unitary Authority','England','[\"Herefordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (54,'Hertfordshire','County','England','[\"Hertfordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (55,'Isle of Wight','County and Unitary Authority','England','[\"Isle of Wight\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (56,'Isles of Scilly','Sui Generis Unitary Authority','England','[\"Cornwall\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (57,'Kent','County','England','[\"Kent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (58,'Kingston upon Hull','Unitary Authority','England','[\"East Riding of Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (59,'Lancashire','County','England','[\"Lancashire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (60,'Leicester','Unitary Authority','England','[\"Leicestershire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (61,'Leicestershire','County','England','[\"Leicestershire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (62,'Lincolnshire','County','England','[\"Lincolnshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (63,'Luton','Unitary Authority','England','[\"Bedfordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (64,'Medway','Unitary Authority','England','[\"Kent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (65,'Merseyside','County','England','[\"Merseyside\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (66,'Middlesbrough','Unitary Authority','England','[\"North Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (67,'Milton Keynes','Unitary Authority','England','[\"Buckinghamshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (68,'Norfolk','County','England','[\"Norfolk\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (69,'North East Lincolnshire','Unitary Authority','England','[\"Lincolnshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (70,'North Lincolnshire','Unitary Authority','England','[\"Lincolnshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (71,'North Northamptonshire','Unitary Authority','England','[\"Northamptonshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (72,'North Somerset','Unitary Authority','England','[\"Somerset\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (73,'North Yorkshire','Unitary Authority','England','[\"North Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (74,'Northumberland','County and Unitary Authority','England','[\"Northumberland\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (75,'Nottingham','Unitary Authority','England','[\"Nottinghamshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (76,'Nottinghamshire','County','England','[\"Nottinghamshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (77,'Oxfordshire','County','England','[\"Oxfordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (78,'Peterborough','Unitary Authority','England','[\"Cambridgeshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (79,'Plymouth','Unitary Authority','England','[\"Devon\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (80,'Portsmouth','Unitary Authority','England','[\"Hampshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (81,'Redcar and Cleveland','Unitary Authority','England','[\"North Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (82,'Reading','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (83,'Rutland','County and Unitary Authority','England','[\"Rutland\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (84,'Shropshire','Unitary Authority','England','[\"Shropshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (85,'Slough','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (86,'Somerset','Unitary Authority','England','[\"Somerset\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (87,'South Gloucestershire','Unitary Authority','England','[\"Gloucestershire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (88,'South Yorkshire','County','England','[\"South Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (89,'Southend-on-Sea','Unitary Authority','England','[\"Essex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (90,'Southampton','Unitary Authority','England','[\"Hampshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (91,'Staffordshire','County','England','[\"Staffordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (92,'Stockton-on-Tees','Unitary Authority','England','[\"Durham\", \"North Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (93,'Stoke-on-Trent','Unitary Authority','England','[\"Staffordshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (94,'Suffolk','County','England','[\"Suffolk\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (95,'Surrey','County','England','[\"Surrey\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (96,'Swindon','Unitary Authority','England','[\"Wiltshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (97,'Telford and Wrekin','Unitary Authority','England','[\"Shropshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (98,'Thurrock','Unitary Authority','England','[\"Essex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (99,'Torbay','Unitary Authority','England','[\"Devon\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (100,'Tyne and Wear','County','England','[\"Tyne and Wear\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (101,'Warrington','Unitary Authority','England','[\"Cheshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (102,'Warwickshire','County','England','[\"Warwickshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (103,'West Berkshire','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (104,'West Midlands','County','England','[\"West Midlands\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (105,'West Northamptonshire','Unitary Authority','England','[\"Northamptonshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (106,'West Sussex','County','England','[\"West Sussex\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (107,'West Yorkshire','County','England','[\"West Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (108,'Westmorland and Furness','Unitary Authority','England','[\"Cumbria\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (109,'Wiltshire','Unitary Authority','England','[\"Wiltshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (110,'Windsor and Maidenhead','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (111,'Wokingham','Unitary Authority','England','[\"Berkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (112,'Worcestershire','County','England','[\"Worcestershire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (113,'York','Unitary Authority','England','[\"North Yorkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (114,'Aberdeen City','Council Area','Scotland','[\"Aberdeenshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (115,'Aberdeenshire','Council Area','Scotland','[\"Aberdeenshire\", \"Banffshire\", \"Kincardineshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (116,'Angus','Council Area','Scotland','[\"Angus\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (117,'Argyll and Bute','Council Area','Scotland','[\"Argyll\", \"Buteshire\", \"Dunbartonshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (118,'Clackmannanshire','Council Area','Scotland','[\"Clackmannanshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (119,'Dumfries and Galloway','Council Area','Scotland','[\"Dumfriesshire\", \"Kirkcudbrightshire\", \"Wigtownshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (120,'Dundee City','Council Area','Scotland','[\"Angus\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (121,'East Ayrshire','Council Area','Scotland','[\"Ayrshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (122,'East Dunbartonshire','Council Area','Scotland','[\"Dunbartonshire\", \"Lanarkshire\", \"Stirlingshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (123,'East Lothian','Council Area','Scotland','[\"East Lothian\", \"Midlothian\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (124,'East Renfrewshire','Council Area','Scotland','[\"Renfrewshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (125,'City of Edinburgh','Council Area','Scotland','[\"Midlothian\", \"West Lothian\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (126,'Falkirk','Council Area','Scotland','[\"Stirlingshire\", \"West Lothian\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (127,'Fife','Council Area','Scotland','[\"Fife\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (128,'Glasgow City','Council Area','Scotland','[\"Lanarkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (129,'Highland','Council Area','Scotland','[\"Argyll\", \"Caithness\", \"Inverness-shire\", \"Moray\", \"Nairnshire\", \"Ross and Cromarty\", \"Sutherland\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (130,'Inverclyde','Council Area','Scotland','[\"Renfrewshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (131,'Moray','Council Area','Scotland','[\"Banffshire\", \"Moray\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (132,'Midlothian','Council Area','Scotland','[\"Midlothian\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (133,'North Ayrshire','Council Area','Scotland','[\"Ayrshire\", \"Buteshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (134,'North Lanarkshire','Council Area','Scotland','[\"Dunbartonshire\", \"Lanarkshire\", \"Stirlingshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (135,'Orkney Islands','Council Area','Scotland','[\"Orkney\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (136,'Na h-Eileanan Siar','Council Area','Scotland','[\"Inverness-shire\", \"Ross and Cromarty\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (137,'Perth and Kinross','Council Area','Scotland','[\"Kinross-shire\", \"Perthshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (138,'Renfrewshire','Council Area','Scotland','[\"Renfrewshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (139,'Scottish Borders','Council Area','Scotland','[\"Berwickshire\", \"East Lothian\", \"Midlothian\", \"Peebles\", \"Roxburghshire\", \"Selkirkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (140,'Shetland Islands','Council Area','Scotland','[\"Zetland\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (141,'South Ayrshire','Council Area','Scotland','[\"Ayrshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (142,'South Lanarkshire','Council Area','Scotland','[\"Lanarkshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (143,'Stirling','Council Area','Scotland','[\"Perthshire\", \"Stirlingshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (144,'West Dunbartonshire','Council Area','Scotland','[\"Dunbartonshire\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (145,'West Lothian','Council Area','Scotland','[\"Midlothian\", \"West Lothian\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (146,'Blaenau Gwent','County Borough','Wales','[\"Gwent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (147,'Bridgend','County Borough','Wales','[\"Mid Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (148,'Caerphilly','County Borough','Wales','[\"Gwent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (149,'Cardiff','County','Wales','[\"South Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (150,'Carmarthenshire','County','Wales','[\"Dyfed\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (151,'Ceredigion','County','Wales','[\"Dyfed\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (152,'Conwy','County Borough','Wales','[\"Clwyd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (153,'Denbighshire','County','Wales','[\"Clwyd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (154,'Flintshire','County','Wales','[\"Clwyd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (155,'Isle of Anglesey','County','Wales','[\"Gwynedd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (156,'Merthyr Tydfil','County Borough','Wales','[\"Mid Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (157,'Monmouthshire','County','Wales','[\"Gwent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (158,'Neath Port Talbot','County Borough','Wales','[\"West Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (159,'Newport','County Borough','Wales','[\"Gwent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (160,'Pembrokeshire','County','Wales','[\"Dyfed\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (161,'Powys','County','Wales','[\"Powys\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (162,'Rhondda Cynon Taf','County Borough','Wales','[\"Mid Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (163,'Swansea','County','Wales','[\"West Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (164,'Torfaen','County Borough','Wales','[\"Gwent\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (165,'Vale of Glamorgan','County Borough','Wales','[\"South Glamorgan\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (166,'Wrexham','County Borough','Wales','[\"Clwyd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (167,'Carlow','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (168,'Cavan','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (169,'Clare','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (170,'Cork','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (171,'Donegal','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (172,'Dublin','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (173,'Galway','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (174,'Kerry','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (175,'Kildare','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (176,'Kilkenny','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (177,'Laois','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (178,'Leitrim','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (179,'Limerick','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (180,'Longford','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (181,'Louth','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (182,'Mayo','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (183,'Meath','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (184,'Monaghan','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (185,'Offaly','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (186,'Roscommon','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (187,'Sligo','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (188,'Tipperary','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (189,'Waterford','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (190,'Westmeath','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (191,'Wexford','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (192,'Wicklow','County','Ireland',NULL,80,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (193,'Antrim and Newtownabbey','District','Northern Ireland','[\"Antrim\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (194,'Ards and North Down','District','Northern Ireland','[\"Down\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (195,'Armagh City, Banbridge and Craigavon','District','Northern Ireland','[\"Armagh\", \"Down\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (196,'Belfast','District','Northern Ireland','[\"Antrim\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (197,'Causeway Coast and Glens','District','Northern Ireland','[\"Antrim\", \"Derry\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (198,'Derry City and Strabane','District','Northern Ireland','[\"Derry\", \"Tyrone\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (199,'Fermanagh and Omagh','District','Northern Ireland','[\"Fermanagh\", \"Tyrone\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (200,'Lisburn and Castlereagh','District','Northern Ireland','[\"Antrim\", \"Down\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (201,'Mid and East Antrim','District','Northern Ireland','[\"Antrim\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (202,'Mid Ulster','District','Northern Ireland','[\"Derry\", \"Tyrone\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (203,'Newry, Mourne and Down','District','Northern Ireland','[\"Armagh\", \"Down\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (204,'Grouville','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (205,'Saint Brélade','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (206,'Saint Clement','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (207,'Saint Helier','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (208,'Saint John','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (209,'Saint Lawrence','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (210,'Saint Martin, JE','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (211,'Saint Mary','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (212,'Saint Ouen','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (213,'Saint Peter','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (214,'Saint Saviour, JE','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (215,'Trinity','Parish','Jersey',NULL,NULL,31);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (216,'Castel','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (217,'Forest','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (218,'Saint Andrew','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (219,'Alderney','Parish','Guernsey','[\"Alderney\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (220,'Saint Martin, GG','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (221,'Saint Peter Port','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (222,'Sark','Parish','Guernsey','[\"Sark\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (223,'Saint Pierre du Bois','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (224,'Saint Sampson','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (225,'Saint Saviour, GG','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (226,'Torteval','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (227,'Vale','Parish','Guernsey','[\"Guernsey\"]',NULL,26);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (228,'Gwynedd','County','Wales','[\"Gwynedd\"]',186,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (230,'Auvergne-Rhône-Alpes','Region','France','[\"Ain\", \"Allier\", \"Ardèche\", \"Cantal\", \"Drôme\", \"Isère\", \"Loire\", \"Haute-Loire\", \"Puy-de-Dôme\", \"Rhône\", \"Savoie\", \"Haute-Savoie\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (231,'Bourgogne-Franche-Comté','Region','France','[\"Côte-d\'Or\", \"Doubs\", \"Jura, FR\", \"Nièvre\", \"Haute-Saône\", \"Saône-et-Loire\", \"Yonne\", \"Territoire de Belfort\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (232,'Centre-Val de Loire','Region','France','[\"Cher\", \"Eure-et-Loir\", \"Indre\", \"Indre-et-Loire\", \"Loir-et-Cher\", \"Loiret\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (233,'Grand Est','Region','France','[\"Ardennes\", \"Aube\", \"Marne\", \"Haute-Marne\", \"Meurthe-et-Moselle\", \"Meuse\", \"Moselle\", \"Bas-Rhin\", \"Haut-Rhin\", \"Vosges\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (234,'Guadeloupe','Region','France',NULL,60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (235,'Hauts-de-France','Region','France','[\"Aisne\", \"Nord\", \"Oise\", \"Pas-de-Calais\", \"Somme\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (236,'Île-de-France','Region','France','[\"Paris\", \"Seine-et-Marne\", \"Yvelines\", \"Essonne\", \"Hauts-de-Seine\", \"Seine-Saint-Denis\", \"Val-de-Marne\", \"Val-d\'Oise\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (237,'Martinique','Region','France',NULL,60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (238,'Mayotte','Region','France',NULL,60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (239,'Nouvelle-Aquitaine','Region','France','[\"Charente\", \"Charente-Maritime\", \"Corrèze\", \"Creuse\", \"Dordogne\", \"Gironde\", \"Landes\", \"Lot-et-Garonne\", \"Pyrénées-Atlantiques\", \"Deux-Sèvres\", \"Vienne\", \"Haute-Vienne\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (240,'Pays de la Loire','Region','France','[\"Loire-Atlantique\", \"Maine-et-Loire\", \"Mayenne\", \"Sarthe\", \"Vendée\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (241,'Provence-Alpes-Côte d\'Azur','Region','France','[\"Alpes-de-Haute-Provence\", \"Hautes-Alpes\", \"Alpes-Maritimes\", \"Bouches-du-Rhône\", \"Var\", \"Vaucluse\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (242,'Bretagne','Region','France','[\"Côtes-d\'Armor\", \"Finistère\", \"Ille-et-Vilaine\", \"Morbihan\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (243,'Corse','Region','France','[\"Corse-du-Sud\", \"Haute-Corse\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (244,'Guyane','Region','France','[\"French Guiana\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (245,'Normandie','Region','France','[\"Calvados\", \"Eure\", \"Manche\", \"Orne\", \"Seine-Maritime\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (246,'Occitanie','Region','France','[\"Ariège\", \"Aude\", \"Aveyron\", \"Gard\", \"Haute-Garonne\", \"Gers\", \"Hérault\", \"Lot\", \"Lozère\", \"Hautes-Pyrénées\", \"Pyrénées-Orientales\", \"Tarn\", \"Tarn-et-Garonne\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (247,'La Réunion','Region','France','[\"Réunion\"]',60,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (248,'Capellen','Canton','Luxembourg','[\"Kapellen\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (249,'Clervaux','Canton','Luxembourg','[\"Klierf\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (250,'Diekirch','Canton','Luxembourg',NULL,101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (251,'Echternach','Canton','Luxembourg','[\"Iechternach\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (252,'Esch-sur-Alzette','Canton','Luxembourg','[\"Esch-Uelzecht\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (253,'Grevenmacher','Canton','Luxembourg','[\"Gréiwemaacher\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (254,'Luxembourg, LU','Canton','Luxembourg','[\"Lëtzebuerg\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (255,'Mersch','Canton','Luxembourg','[\"Miersch\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (256,'Redange','Canton','Luxembourg','[\"Réiden\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (257,'Remich','Canton','Luxembourg','[\"Réimech\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (258,'Vianden','Canton','Luxembourg','[\"Veianen\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (259,'Wiltz','Canton','Luxembourg','[\"Wolz\"]',101,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (260,'Monaco','Country','Monaco',NULL,114,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (261,'Andorra la Vella','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (262,'Canillo','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (263,'Encamp','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (264,'Escaldes–Engordany','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (265,'La Massana','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (266,'Ordino','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (267,'Sant Julià de Lòria','Parish','Andorra',NULL,4,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (268,'Andalucía','Autonomous Community','Spain','[\"Andalusia\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (269,'Aragón','Autonomous Community','Spain','[\"Aragon\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (270,'Asturias','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (271,'Canarias','Autonomous Community','Spain','[\"Canary Islands\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (272,'Cantabria','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (273,'Castilla y León','Autonomous Community','Spain','[\"Castile and León\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (274,'Castilla–La Mancha','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (275,'Catalunya','Autonomous Community','Spain','[\"Catalonia\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (276,'Ceuta','Autonomous City','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (277,'Comunidad de Madrid','Autonomous Community','Spain','[\"Madrid\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (278,'Comunitat Valenciana','Autonomous Community','Spain','[\"Valencia\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (279,'Euskadi','Autonomous Community','Spain','[\"Basque Country\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (280,'Extremadura','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (281,'Galicia','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (282,'Illes Balears','Autonomous Community','Spain','[\"Balearic Islands\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (283,'La Rioja','Autonomous Community','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (284,'Melilla','Autonomous City','Spain',NULL,165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (285,'Navarra','Autonomous Community','Spain','[\"Navarre\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (286,'Región de Murcia','Autonomous Community','Spain','[\"Murcia\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (287,'Plazas de soberanía','Unincorporated Area','Spain','[\"Strongholds of Sovereignty\"]',165,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (288,'Gibraltar','Territory','Gibraltar',NULL,NULL,23);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (289,'Açores','Autonomous Region','Portugal','[\"Azores\"]',140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (290,'Aveiro','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (291,'Beja','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (292,'Braga','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (293,'Bragança','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (294,'Castelo Branco','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (295,'Coimbra','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (296,'Évora','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (297,'Faro','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (298,'Guarda','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (299,'Leiria','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (300,'Lisboa','District','Portugal','[\"Lisbon\"]',140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (301,'Madeira','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (302,'Portalegre','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (303,'Porto','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (304,'Santarém','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (305,'Setúbal','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (306,'Viana do Castelo','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (307,'Vila Real','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (308,'Viseu','District','Portugal',NULL,140,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (309,'Antwerpen','Province','Belgium','[\"Antwerp\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (310,'Brabant wallon','Province','Belgium','[\"Walloon Brabant\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (311,'Brussels-Capital Region','Region','Belgium','[\"Brussels\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (312,'Hainaut','Province','Belgium',NULL,17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (313,'Liège','Province','Belgium',NULL,17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (314,'Limburg, BE','Region','Belgium',NULL,17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (315,'Luxembourg, BE','Province','Belgium',NULL,17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (316,'Namur','Region','Belgium',NULL,17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (317,'Oost-Vlaanderen','Province','Belgium','[\"East Flanders\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (318,'Vlaams-Brabant','Province','Belgium','[\"Flemish Brabant\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (319,'West-Vlaanderen','Region','Belgium','[\"West Flanders\"]',17,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (320,'Aargau','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (321,'Appenzell Ausserrhoden','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (322,'Appenzell Innerrhoden','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (323,'Basel-Landschaft','Canton','Switzerland','[\"Basel-Country\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (324,'Basel-Stadt','Canton','Switzerland','[\"Basel-City\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (325,'Bern','Canton','Switzerland','[\"Berne\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (326,'Fribourg','Canton','Switzerland','[\"Freiburg\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (327,'Genève','Canton','Switzerland','[\"Geneva\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (328,'Glarus','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (329,'Graubünden','Canton','Switzerland','[\"Grisons\", \"Grischun\", \"Grigioni\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (330,'Jura, CH','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (331,'Luzern','Canton','Switzerland','[\"Lucerne\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (332,'Neuchâtel','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (333,'Nidwalden','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (334,'Obwalden','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (335,'Schaffhausen','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (336,'Schwyz','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (337,'Solothurn','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (338,'Sankt Gallen','Canton','Switzerland','[\"Saint Gallen\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (339,'Thurgau','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (340,'Ticino','Canton','Switzerland','[\"Tessin\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (341,'Uri','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (342,'Valais/Wallis','Canton','Switzerland','[\"Valais\", \"Wallis\"]',170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (343,'Vaud','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (344,'Zug','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (345,'Zürich','Canton','Switzerland',NULL,170,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (346,'Abruzzo','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (347,'Basilicata','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (348,'Calabria','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (349,'Campania','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (350,'Emilia-Romagna','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (351,'Friuli-Venezia Giulia','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (352,'Lazio','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (353,'Liguria','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (354,'Lombardia','Region','Italy','[\"Lombardy\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (355,'Marche','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (356,'Molise','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (357,'Piemonte','Region','Italy','[\"Piedmont\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (358,'Puglia','Region','Italy','[\"Apulia\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (359,'Sardegna','Region','Italy','[\"Sardinia\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (360,'Sicilia','Region','Italy','[\"Sicily\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (361,'Trentino-Alto Adige/Südtirol','Region','Italy','[\"Trentino-South Tyrol\", \"Trentino-Alto Adige\", \"Trentino-Südtirol\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (362,'Toscana','Region','Italy','[\"Tuscany\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (363,'Umbria','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (364,'Valle d\'Aosta','Region','Italy','[\"Aosta Valley\"]',82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (365,'Veneto','Region','Italy',NULL,82,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (366,'Baden-Württemberg','Flächenländer','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (367,'Bayern','Flächenländer','Germany','[\"Bavaria\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (368,'Berlin','Stadtstaaten','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (369,'Brandenburg','Flächenländer','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (370,'Bremen','Stadtstaaten','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (371,'Hamburg','Stadtstaaten','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (372,'Hessen','Flächenländer','Germany','[\"Hesse\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (373,'Mecklenburg-Vorpommern','Flächenländer','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (374,'Niedersachsen','Flächenländer','Germany','[\"Lower Saxony\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (375,'Nordrhein-Westfalen','Flächenländer','Germany','[\"North Rhine-Westphalia\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (376,'Rheinland-Pfalz','Flächenländer','Germany','[\"Rhineland-Palatinate\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (377,'Saarland','Flächenländer','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (378,'Sachsen','Flächenländer','Germany','[\"Saxony\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (379,'Sachsen-Anhalt','Flächenländer','Germany','[\"Saxony-Anhalt\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (380,'Schleswig-Holstein','Flächenländer','Germany',NULL,64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (381,'Thüringen','Flächenländer','Germany','[\"Thuringia\"]',64,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (382,'Bonaire','Special Municipality','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (383,'Drenthe','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (384,'Flevoland','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (385,'Fryslân','Province','Netherlands','[\"Friesland\"]',123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (386,'Gelderland','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (387,'Groningen','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (388,'Limburg, NL','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (389,'Noord-Brabant','Province','Netherlands','[\"North Brabant\"]',123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (390,'Noord-Holland','Province','Netherlands','[\"North Holland\"]',123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (391,'Overijssel','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (392,'Saba','Special Municipality','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (393,'Sint Eustatius','Special Municipality','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (394,'Utrecht','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (395,'Zeeland','Province','Netherlands',NULL,123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (396,'Zuid-Holland','Province','Netherlands','[\"South Holland\"]',123,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (397,'Region Hovedstaden','Region','Denmark','[\"Capital Region of Denmark\"]',45,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (398,'Region Midtjylland','Region','Denmark','[\"Central Denmark Region\"]',45,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (399,'Region Nordjylland','Region','Denmark','[\"North Denmark Region\"]',45,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (400,'Region Sjælland','Region','Denmark','[\"Region Zealand\"]',45,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (401,'Region Syddanmark','Region','Denmark','[\"Region of Southern Denmark\"]',45,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (402,'Eysturoyar sýsla','Sýsla','Faroe Islands','[\"Eysturoy Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (403,'Norðoya sýsla','Sýsla','Faroe Islands','[\"Norðoyar Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (404,'Sandoyar sýsla','Sýsla','Faroe Islands','[\"Sandoy Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (405,'Streymoyar sýsla','Sýsla','Faroe Islands','[\"Streymoy Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (406,'Suðuroyar sýsla','Sýsla','Faroe Islands','[\"Suðuroy Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (407,'Vága sýsla','Sýsla','Faroe Islands','[\"Vágar Region\"]',NULL,20);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (408,'Balzers','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (409,'Eschen','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (410,'Gamprin','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (411,'Mauren','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (412,'Planken','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (413,'Ruggell','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (414,'Schaan','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (415,'Schellenberg','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (416,'Triesen','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (417,'Triesenberg','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (418,'Vaduz','Municipality','Liechtenstein',NULL,99,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (419,'Acquaviva','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (420,'Borgo Maggiore','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (421,'Chiesanuova','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (422,'Domagnano','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (423,'Faetano','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (424,'Fiorentino','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (425,'Montegiardino','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (426,'San Marino','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (427,'Serravalle','Castello','San Marino',NULL,150,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (428,'Città del Vaticano','Country','Vatican City',NULL,191,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (429,'Reġjun Għawdex','Region','Malta','[\"Gozo Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (430,'Reġjun Lvant','Region','Malta','[\"Eastern Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (431,'Reġjun Nofsinhar','Region','Malta','[\"Southern Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (432,'Reġjun Punent','Region','Malta','[\"Western Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (433,'Reġjun tal-Port','Region','Malta','[\"Port Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (434,'Reġjun Tramuntana','Region','Malta','[\"Northern Region\"]',107,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (435,'Burgenland','Land','Austria',NULL,10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (436,'Kärnten','Land','Austria','[\"Carinthia\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (437,'Nieder­österreich','Land','Austria','[\"Lower Austria\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (438,'Oberösterreich','Land','Austria','[\"Upper Austria\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (439,'Salzburg','Land','Austria',NULL,10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (440,'Steiermark','Land','Austria','[\"Styria\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (441,'Tirol','Land','Austria','[\"Tyrol\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (442,'Vorarlberg','Land','Austria',NULL,10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (443,'Wien','Land','Austria','[\"Vienna\"]',10,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (444,'Jihočeský kraj','Region','Czech Republic','[\"South Bohemian Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (445,'Jihomoravský kraj','Region','Czech Republic','[\"South Moravian Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (446,'Karlovarský kraj','Region','Czech Republic','[\"Karlovy Vary Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (447,'Královéhradecký kraj','Region','Czech Republic','[\"Hradec Králové Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (448,'Kraj Vysočina','Region','Czech Republic','[\"Vysočina Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (449,'Liberecký kraj','Region','Czech Republic','[\"Liberec Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (450,'Moravskoslezský kraj','Region','Czech Republic','[\"Moravian-Silesian Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (451,'Olomoucký kraj','Region','Czech Republic','[\"Olomouc Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (452,'Pardubický kraj','Region','Czech Republic','[\"Pardubice Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (453,'Plzeňský kraj','Region','Czech Republic','[\"Plzeň Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (454,'Praha','Region','Czech Republic','[\"Prague\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (455,'Středočeský kraj','Region','Czech Republic','[\"Central Bohemian Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (456,'Ústecký kraj','Region','Czech Republic','[\"Ústí nad Labem Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (457,'Zlínský kraj','Region','Czech Republic','[\"Zlín Region\"]',43,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (458,'Dolnośląskie','Voivodeship','Poland','[\"Lower Silesian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (459,'Kujawsko-Pomorskie','Voivodeship','Poland','[\"Kuyavian–Pomeranian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (460,'Łódzkie','Voivodeship','Poland','[\"Łódź Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (461,'Lubelskie','Voivodeship','Poland','[\"Lublin Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (462,'Lubuskie','Voivodeship','Poland','[\"Lubusz Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (463,'Małopolskie','Voivodeship','CPoland','[\"Lesser Poland Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (464,'Mazowieckie','Voivodeship','Poland','[\"Masovian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (465,'Opolskie','Voivodeship','Poland','[\"Opole Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (466,'Podkarpackie','Voivodeship','Poland','[\"Subcarpathian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (467,'Podlaskie','Voivodeship','Poland','[\"Podlaskie Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (468,'Pomorskie','Voivodeship','Poland','[\"Pomeranian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (469,'Śląskie','Voivodeship','Poland','[\"Silesian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (470,'Świętokrzyskie','Voivodeship','Poland','[\"Holy Cross Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (471,'Warmińsko-Mazurskie','Voivodeship','Poland','[\"Warmian–Masurian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (472,'Wielkopolskie','Voivodeship','Poland','[\"Greater Poland Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (473,'Zachodniopomorskie','Voivodeship','Poland','[\"West Pomeranian Voivodeship\"]',139,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (474,'Banskobystrický kraj','Region','Slovakia','[\"Banská Bystrica Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (475,'Bratislavský kraj','Region','Slovakia','[\"Bratislava Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (476,'Košický kraj','Region','Slovakia','[\"Košice Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (477,'Nitriansky kraj','Region','Slovakia','[\"Nitra Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (478,'Prešovský kraj','Region','Slovakia','[\"Prešov Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (479,'Trenčiansky kraj','Region','Slovakia','[\"Trenčín Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (480,'Trnavský kraj','Region','Slovakia','[\"Trnava Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (481,'Žilinský kraj','Region','Slovakia','[\"Žilina Region\"]',158,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (482,'Baranya','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (483,'Bács-Kiskun','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (484,'Békés','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (485,'Borsod-Abaúj-Zemplén','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (486,'Budapest','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (487,'Csongrád-Csanád','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (488,'Fejér','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (489,'Győr-Moson-Sopron','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (490,'Hajdú-Bihar','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (491,'Heves','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (492,'Jász-Nagykun-Szolnok','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (493,'Komárom-Esztergom','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (494,'Nógrád','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (495,'Pest','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (496,'Somogy','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (497,'Szabolcs-Szatmár-Bereg','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (498,'Tolna','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (499,'Vas','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (500,'Veszprém','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (501,'Zala','County','Hungary',NULL,74,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (502,'Gorenjska','Statistical Region','Slovenia','[\"Jesenice\", \"Kranj\", \"Radovljica\", \"Škofja Loka\", \"Tržič\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (503,'Goriška','Statistical Region','Slovenia','[\"Ajdovščina\", \"Idrija\", \"Nova Gorica\", \"Tolmin\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (504,'Jugovzhodna Slovenija','Statistical Region','Slovenia','[\"Črnomelj\", \"Kočevje\", \"Metlika\", \"Novo Mesto\", \"Ribnica\", \"Trebnje\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (505,'Koroška','Statistical Region','Slovenia','[\"Dravograd\", \"Radlje ob Dravi\", \"Ravne na Koroškem\", \"Slovenj Gradec\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (506,'Obalno-Kraška','Statistical Region','Slovenia','[\"Izola\", \"Koper\", \"Piran\", \"Sežana\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (507,'Osrednjeslovenska','Statistical Region','Slovenia','[\"Domžale\", \"Grosuplje\", \"Kamnik\", \"Ljubljana\", \"Logatec\", \"Vrhnika\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (508,'Podravska','Statistical Region','Slovenia','[\"Lenart\", \"Maribor\", \"Ormož\", \"Pesnica\", \"Ptuj\", \"Ruše\", \"Slovenska Bistrica\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (509,'Pomurska','Statistical Region','Slovenia','[\"Gornja Radgona\", \"Lendava\", \"Ljutomer\", \"Murska Sobota\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (510,'Posavska','Statistical Region','Slovenia','[\"Brežice\", \"Krško\", \"Sevnica\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (511,'Primorsko-Notranjska','Statistical Region','Slovenia','[\"Cerknica\", \"Ilirska Bistrica\", \"Postojna\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (512,'Savinjska','Statistical Region','Slovenia','[\"Celje\", \"Laško\", \"Mozirje\", \"Slovenske Konjice\", \"Šentjur\", \"Šmarje pri Jelšah\", \"Velenje\", \"Žalec\"]',159,NULL);
INSERT INTO `` (`idEuropeanRegion`,`Name`,`Type`,`Country`,`OtherRegion`,`idCountry`,`idTerritory`) VALUES (513,'Zasavska','Statistical Region','Slovenia','[\"Hrastnik\", \"Litija\", \"Trbovlje\", \"Zagorje ob Savi\"]',159,NULL);
